servicename: <+service.identifier>
fullimagepath: <+artifacts.primary.image>
imagepath: <+artifacts.primary.imagePath>
version: version98
replicas: 1
port: 5000
resourcelimits:
 cpurequest: "100m"
 memrequest: "64Mi"
path: "/hello"
createingress: false